[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install && cd ../frontend && yarn install && yarn build"
watchPatterns = ["backend/**", "frontend/**"]

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
healthcheckPath = "/health"
healthcheckTimeout = 5 